const INCENTIVES_DB = [
  {
    "AFUE" : null,
    "amount" : 400.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Central AC",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 12,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : null,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1d80-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "central_ac",
    "region" : null,
    "SEER2" : 15.2,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 500.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Central AC",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 12,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : null,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1d8a-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "central_ac",
    "region" : null,
    "SEER2" : 16,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 600.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Central AC",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 13,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : null,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1d94-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "central_ac",
    "region" : null,
    "SEER2" : 18,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 450.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Air Source Heat Pump",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 11.7,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : 7.8,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1da8-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : null,
    "SEER2" : 15.2,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 550.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Air Source Heat Pump",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 12,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : 9,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1db2-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : null,
    "SEER2" : 16,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 750.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Austin Energy - Air Source Heat Pump",
    "display_text" : "Austin Energy rebate (instant)",
    "documentation_url" : "https:\/\/savings.austinenergy.com\/residential\/offerings\/cooling-and-heating\/ac",
    "EER2" : 13,
    "energy_source" : "electricity",
    "entity_id" : "90da1e48-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : 10,
    "existing_system_required" : true,
    "HSPF2" : 9,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1dbc-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : null,
    "SEER2" : 17,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : 0.92,
    "amount" : 675.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "Texas Gas - Furnace",
    "display_text" : "Texas Gas rebate (after purchase)",
    "documentation_url" : "https:\/\/www.texasgasservice.com\/media\/TGS\/EnergyEfficiency\/CentralTexas\/2022Updates\/LearnMoreForms\/Residential\/Residential-NaturalGasFurnace-FactSheet.pdf",
    "EER2" : null,
    "energy_source" : "natural_gas",
    "entity_id" : "90da1ea2-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : null,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1dc6-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "furnace",
    "region" : null,
    "SEER2" : null,
    "tonnage" : null,
    "ventiliation_type" : null
  },
  {
    "AFUE" : null,
    "amount" : 600.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - Central AC",
    "display_text" : "Federal tax credit - AC (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQbyUAG",
    "EER2" : 12,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : null,
    "HVAC_system_type" : "split",
    "incentives_id" : "90da1dda-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "central_ac",
    "region" : null,
    "SEER2" : 16,
    "tonnage" : null,
    "ventiliation_type" : "ducted"
  },
  {
    "AFUE" : null,
    "amount" : 600.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - Central AC",
    "display_text" : "Federal tax credit - AC (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQbyUAG",
    "EER2" : 12,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : null,
    "HVAC_system_type" : "packaged",
    "incentives_id" : "90da1de4-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "central_ac",
    "region" : null,
    "SEER2" : 15.2,
    "tonnage" : null,
    "ventiliation_type" : "ducted"
  },
  {
    "AFUE" : null,
    "amount" : 2000.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - ASHP",
    "display_text" : "Federal tax credit - heat pump (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQbyUAG",
    "EER2" : 11.7,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : 7.8,
    "HVAC_system_type" : "split",
    "incentives_id" : "90da1dee-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : "south",
    "SEER2" : 15.2,
    "tonnage" : null,
    "ventiliation_type" : "ducted"
  },
  {
    "AFUE" : null,
    "amount" : 2000.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - ASHP",
    "display_text" : "Federal tax credit - heat pump (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQbyUAG",
    "EER2" : 10.6,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : 7.2,
    "HVAC_system_type" : "packaged",
    "incentives_id" : "90da1df8-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : "south",
    "SEER2" : 15.2,
    "tonnage" : null,
    "ventiliation_type" : "ducted"
  },
  {
    "AFUE" : null,
    "amount" : 2000.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - ASHP",
    "display_text" : "Federal tax credit - heat pump (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQbyUAG",
    "EER2" : 12,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : 9,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1e02-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "ashp",
    "region" : "south",
    "SEER2" : 16,
    "tonnage" : null,
    "ventiliation_type" : "ductless"
  },
  {
    "AFUE" : 0.97,
    "amount" : 600.0,
    "capacity" : null,
    "COP" : null,
    "display_name" : "25C - Furnace",
    "display_text" : "Federal tax credit - furnace (next year)",
    "documentation_url" : "https:\/\/cee1.my.site.com\/s\/resources?id=a0V2R00000sUQcXUAW",
    "EER2" : null,
    "energy_source" : null,
    "entity_id" : "90da1e34-c29a-11ed-a851-3aebb006c675",
    "existing_system_age" : null,
    "existing_system_required" : null,
    "HSPF2" : null,
    "HVAC_system_type" : null,
    "incentives_id" : "90da1e16-c29a-11ed-a851-3aebb006c675",
    "last_updated" : "3\/14\/2023",
    "product_type" : "furnace",
    "region" : null,
    "SEER2" : null,
    "tonnage" : null,
    "ventiliation_type" : null
  }
]

export { INCENTIVES_DB }

