const INCENTIVES_DB = [
  {
    'amount': '$600',
    'capacity': null,
    'compressor_type': null,
    'display_name': '25C - Central AC',
    'display_text': 'Federal Tax Credit for AC (next year)',
    'SEER2': 16.00,
    'EER2': 12.00,
    'AFUE': null,
    'HSPF2': null,
    'COP': null,
    'energy_source': null,
    'entity_name': 'IRS',
    'existing_system_age': null,
    'Existing_system_required': 'FALSE',
    'HVAC_system_type': 'Split',
    'incentives_id': '13f004d8-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': null,
  },
  {
    'amount': '$600',
    'capacity': null,
    'compressor_type': null,
    'display_name': '25C - Central AC',
    'display_text': 'Federal Tax Credit for Furnace (next year)',
    'SEER2': null,
    'EER2': null,
    'AFUE': 0.97,
    'HSPF2': null,
    'COP': null,
    'energy_source': null,
    'entity_name': 'IRS',
    'existing_system_age': null,
    'Existing_system_required': 'FALSE',
    'HVAC_system_type': null,
    'incentives_id': '13f00654-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'furnace',
    'region': null,
    'tonnage': null,
    'ventilation_type': null,
  },
  {
    'amount': '$250',
    'capacity': null,
    'compressor_type': 'conventional',
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'SEER2': 15.2,
    'EER2': 12,
    'COP': null,
    'AFUE': null,
    'HSPF2': null,
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': 10,
    'Existing_system_required': 'TRUE',
    'HVAC_system_type': null,
    'incentives_id': '13f00668-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'amount': '$150',
    'capacity': null,
    'compressor_type': 'inverter',
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'SEER2': 15.2,
    'EER2': 12,
    'HSPF2': null,
    'COP': null,
    'AFUE': null,
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': 10,
    'Existing_system_required': 'TRUE',
    'HVAC_system_type': null,
    'incentives_id': '13f00690-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'amount': '$350',
    'capacity': null,
    'compressor_type': null,
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': 10,
    'Existing_system_required': 'TRUE',
    'SEER2': 16,
    'EER2': 13,
    'AFUE': null,
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f006a4-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'amount': '$450',
    'capacity': null,
    'compressor_type': 'conventional',
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'SEER2': 18,
    'EER2': 13,
    'AFUE': null,
    'HSPF2': null,
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': 10,
    'Existing_system_required': 'TRUE',
    'HVAC_system_type': null,
    'incentives_id': '13f006ae-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'amount': '$550',
    'capacity': null,
    'compressor_type': 'inverter',
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': 13,
    'SEER2': 18,
    'HSPF2': null,
    'AFUE': null,
    'COP': null,
    'existing_system_age': 10,
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'Existing_system_required': 'TRUE',
    'HVAC_system_type': null,
    'incentives_id': '13f006c2-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'amount': '$675',
    'capacity': null,
    'compressor_type': null,
    'display_name': 'Texas Gas - Furnace',
    'display_text': 'Texas Gas (instant)',
    'AFUE': 0.92,
    'EER2': null,
    'COP': null,
    'HSPF2': null,
    'SEER2': null,
    'energy_source': 'natural_gas',
    'entity_name': 'Texas Gas',
    'existing_system_age': '',
    'Existing_system_required': '',
    'HVAC_system_type': null,
    'incentives_id': '13f006cc-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'furnace',
    'region': null,
    'tonnage': null,
    'ventilation_type': null,
  },
]
export {INCENTIVES_DB}

