const PRODUCTS_DB = [
  {
    'AFUE': null,
    'AHRI_number': 'tbu_later',
    'capacity': null,
    'compressor_type': 'conventional',
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'AC: 15 SEER2, 12 EER2, single stage',
    'display_equipment_tooltip': 'SEER2 measures cooling across range of temperatures, EER2 measures cooling at high temperatures (95 degrees F). A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Not eligible for any incentives',
    'display_title': 'Basic',
    'EER2': 12,
    'HSPF2': null,
    'HVAC_system_type': 'split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'central_ac',
    'products_id': '78ee813e-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': 15,
    'tonnage': 3,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'AHRI_number': 'tbu_later',
    'capacity': null,
    'compressor_type': 'inverter',
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'AC: 16 SEER2, 13 EER2, variable stage',
    'display_equipment_tooltip': 'SEER2 measures cooling across range of temperatures, EER2 measures cooling at high temperatures (95 degrees F). A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Eligible for some of the incentives',
    'display_title': 'Semi-Efficient',
    'EER2': 13,
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'central_ac',
    'products_id': '78ee81fc-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': 16,
    'tonnage': 3,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'AHRI_number': 'tbu_later',
    'capacity': null,
    'compressor_type': 'inverter',
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'AC: 18 SEER2, 13 EER2, variable stage',
    'display_equipment_tooltip': 'SEER2 measures cooling across range of temperatures, EER2 measures cooling at high temperatures (95 degrees F). A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Eligible for all available incentives',
    'display_title': 'Efficient',
    'EER2': 13,
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'central_ac',
    'products_id': '78ee822e-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': 18,
    'tonnage': 3,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': 0.80,
    'AHRI_number': 'tbu_later',
    'capacity': 60000,
    'compressor_type': null,
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'Furnace: 80% AFUE',
    'display_equipment_tooltip': 'AFUE measures heating efficiency. A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Not eligible for any incentives',
    'display_title': 'Basic',
    'EER2': null,
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'furnace',
    'products_id': '78ee826a-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': 0.92,
    'AHRI_number': 'tbu_later',
    'capacity': 60000,
    'compressor_type': null,
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'Furnace: 92% AFUE',
    'display_equipment_tooltip': 'AFUE measures heating efficiency. A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Eligible for some of the incentives',
    'display_title': 'Semi-Efficient',
    'EER2': null,
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'furnace',
    'products_id': '78ee8288-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': 0.97,
    'AHRI_number': 'tbu_later',
    'capacity': 60000,
    'compressor_type': null,
    'COP': null,
    'display_carbon_reduction': '',
    'display_energy bill': '',
    'display_equipment_detail': null,
    'display_equipment_summary': 'Furnace: 97% AFUE',
    'display_equipment_tooltip': 'AFUE measures heating efficiency. A higher number indicates more efficient.',
    'display_name': 'tbu later',
    'display_picture': null,
    'display_subtitle': 'Eligible for all available incentives',
    'display_title': 'Efficient',
    'EER2': null,
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'Manufacturer': 'tbu_later',
    'Manufacturer_model_number': 'tbu_later',
    'product_type': 'furnace',
    'products_id': '78ee829c-bdd1-11ed-9a5f-3aebb006c675',
    'SEER2': null,
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
]


export {PRODUCTS_DB}
